# Generated by Django 4.0.5 on 2024-02-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nohpt', '0002_book_current_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='current_section',
        ),
        migrations.AddField(
            model_name='section',
            name='audio_path',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='section',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='section',
            name='music_path',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AddField(
            model_name='section',
            name='text',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GeneratedContent',
        ),
    ]
