# Generated by Django 4.0.5 on 2024-02-17 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nohpt', '0003_remove_book_current_section_section_audio_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_books', to='nohpt.section'),
        ),
    ]
