# Generated by Django 4.0.5 on 2024-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nohpt', '0007_alter_section_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='audio_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='music_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
